// server_coursedata.js

const subjects = {
    'tyt-turkce': { name: 'TYT Türkçe', type: 'TYT', topics: ['Sözcükte Anlam', 'Cümlede Anlam', 'Paragrafta Anlam', 'Anlatım Biçimleri', 'Ses Bilgisi', 'Yazım Kuralları', 'Noktalama İşaretleri', 'Sözcükte Yapı', 'Sözcük Türleri', 'Edat-Bağlaç-Ünlem', 'Fiiller', 'Ek Fiil', 'Fiilde Çatı', 'Fiilimsi', 'Cümlenin Öğeleri', 'Cümle Türleri', 'Anlatım Bozuklukları'] },
    'tyt-tarih': { name: 'TYT Tarih', type: 'TYT', topics: ['Tarih ve Zaman', 'İnsanlığın İlk Dönemleri', 'Orta Çağ’da Dünya', 'İlk ve Orta Çağlarda Türk Dünyası', 'İslam Medeniyetinin Doğuşu', 'Türklerin İslamiyet’i Kabulü ve İlk Türk İslam Devletleri', 'Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi', 'Beylikten Devlete Osmanlı Siyaseti', 'Devletleşme Sürecinde Savaşçılar ve Askerler', 'Dünya Gücü Osmanlı', 'Sultan ve Osmanlı Merkez Teşkilatı', 'Klasik Çağda Osmanlı Toplum Düzeni', 'Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti', 'Değişim Çağında Avrupa ve Osmanlı', 'Uluslararası İlişilerde Denge Stratejisi', 'Devrimler Çağında Değişen Devlet-Toplum İlişkileri', 'Sermaye ve Emek', 'XIX. ve XX. Yüzyılda Değişen Gündelik Hayat', 'Milli Mücadele', 'Atatürkçülük ve Türk İnkılabı'] },
    'tyt-cografya': { name: 'TYT Coğrafya', type: 'TYT', topics: ['Doğa, İnsan ve Coğrafya', 'Dünya’nın Şekli ve Hareketleri', 'Coğrafi Konum', 'Harita Bilgisi', 'İklim Bilgisi', 'Atmosfer ve Sıcaklık', 'Basınç ve Rüzgarlar', 'Nemlilik ve Yağış', 'İklim Tipleri', 'Türkiye’nin İklimi', 'Yer’in Şekillenmesi', 'İç Kuvvetler', 'Dış Kuvvetler', 'Türkiye’nin Yer Şekilleri', 'Su Kaynakları', 'Topraklar', 'Bitkiler', 'Nüfus ve Yerleşme', 'Ekonomik Faaliyetler', 'Bölgeler ve Ülkeler', 'Doğal Afetler ve Toplum'] },
    'tyt-felsefe': { name: 'TYT Felsefe', type: 'TYT', topics: ['Felsefeyi Tanıma', 'Felsefe ile Düşünme', 'Varlık Felsefesi', 'Bilgi Felsefesi', 'Bilim Felsefesi', 'Ahlak Felsefesi', 'Din Felsefesi', 'Siyaset Felsefesi', 'Sanat Felsefesi'] },
    'tyt-din-kulturu': { name: 'TYT Din Kültürü', type: 'TYT', topics: ['Bilgi ve İnanç', 'Din ve İslam', 'İslam ve İbadet', 'Ahlaki Tutum ve Davranışlar', 'Hz. Muhammed (S.A.V.)', 'Vahiy ve Akıl', 'İslam Düşüncesinde Yorumlar', 'Din, Kültür ve Medeniyet', 'İslam ve Bilim', 'Yaşayan Dinler'] },
    'tyt-matematik': { name: 'TYT Matematik', type: 'TYT', topics: ['Temel Kavramlar', 'Sayı Basamakları', 'Bölme ve Bölünebilme', 'EBOB - EKOK', 'Rasyonel Sayılar', 'Basit Eşitsizlikler', 'Mutlak Değer', 'Üslü Sayılar', 'Köklü Sayılar', 'Çarpanlara Ayırma', 'Oran Orantı', 'Denklem Çözme', 'Problemler', 'Kümeler', 'Kartezyen Çarpım', 'Mantık', 'Fonksiyonlar', 'Polinomlar', '2. Dereceden Denklemler', 'Permütasyon ve Kombinasyon', 'Olasılık', 'Veri - İstatistik'] },
    'tyt-geometri': { name: 'TYT Geometri', type: 'TYT', topics: ['Temel Kavramlar', 'Doğruda Açılar', 'Üçgende Açılar', 'Özel Açılar', 'Açıortay', 'Kenarortay', 'Eşlik ve Benzerlik', 'Üçgende Alan', 'Açıkenar Bağıntıları', 'Çokgenler', 'Özel Dörtgenler', 'Çember ve Daire', 'Analitik Geometri', 'Katı Cisimler', 'Çemberin Analitiği'] },
    'tyt-fizik': { name: 'TYT Fizik', type: 'TYT', topics: ['Fizik Bilimine Giriş', 'Madde ve Özellikleri', 'Sıvıların Kaldırma Kuvveti', 'Basınç', 'Isı, Sıcaklık ve Genleşme', 'Hareket ve Kuvvet', 'Dinamik', 'İş, Güç ve Enerji', 'Elektrik', 'Manyetizma', 'Dalgalar', 'Optik'] },
    'tyt-kimya': { name: 'TYT Kimya', type: 'TYT', topics: ['Kimya Bilimine Giriş', 'Atom ve Periyodik Cetvel', 'Kimyasal Türler Arası Etkileşimler', 'Maddenin Halleri', 'Doğa ve Kimya', 'Kimyanın Temel Kanunları', 'Mol Kavramı ve Kimyasal Hesaplamalar', 'Asitler- Bazlar- Tuzlar', 'Karışımlar', 'Kimya Her Yerde'] },
    'tyt-biyoloji': { name: 'TYT Biyoloji', type: 'TYT', topics: ['Canlıların Ortak Özellikleri', 'Canlıların Temel Bileşenleri', 'Hücre ve Organelleri', 'Hücre Zarından Madde Geçişi', 'Canlıların Sınıflandırılması', 'Mitoz ve Eşeysiz Üreme', 'Mayoz ve Eşeyli Üreme', 'Kalıtım', 'Ekosistem Ekolojisi', 'Güncel Çevre Sorunları'] },
    'ayt-matematik': { name: 'AYT Matematik', type: 'AYT', topics: ['Fonksiyonlar', '2.Dereceden Denklemler', 'Eşitsizlikler', 'Parabol', 'Polinomlar', 'Trigonometri', 'Logaritma', 'Diziler', 'Limit', 'Türev', 'İntegral'] },
    'ayt-geometri': { name: 'AYT Geometri', type: 'AYT', topics: ['Çemberin Analitiği', 'Dönüşüm Geometrisi', 'Vektörler', 'Uzay Geometri'] },
    'ayt-fizik': { name: 'AYT Fizik', type: 'AYT', topics: ['Vektörler', 'Bağıl Hareket', 'Newtonun Hareket Yasaları', 'Sabit İvmeli Hareket', 'Atışlar', 'İtme ve Momentum', 'Tork', 'Denge', 'Kütle Merkezi', 'Basit Makineler', 'Çembersel Hareket', 'Basit Harmonik Hareket', 'Kütle Çekim', 'Kepler Yasaları', 'Elektriksel Kuvvet ve Alan', 'Elektriksel Potensiyel', 'Düzgün Elektrik Alan ve Sığa', 'Manyetizma ve Elektromanyetik İndüklenme', 'Alternatif Akım', 'Transformatörler', 'Dalga Mekaniği', 'Atom Fiziğine Giriş ve Radyoaktivite', 'Modern Fizik', 'Modern Fiziğin Teknolojideki Uygulamaları'] },
    'ayt-kimya': { name: 'AYT Kimya', type: 'AYT', topics: ['Modern Atom Teorisi', 'Gazlar', 'Sıvı Çözeltiler', 'Kimyasal Tepkimelerde Enerji', 'Kimyasal Tepkimelerde Hız', 'Kimyasal Tepkimelerde Denge', 'Asit-Baz Dengesi', 'Çözünürlük Dengesi', 'Kimya ve Elektrik', 'Karbon Kimyasına Giriş', 'Organik Bileşikler', 'Enerji Kaynakları ve Bilimsel Gelişmeler'] },
    'ayt-biyoloji': { name: 'AYT Biyoloji', type: 'AYT', topics: ['Sinir Sistemi', 'Endokrin Sistem', 'Duyu Organları', 'Destek ve Hareket Sistemi', 'Sindirim Sistemi', 'Dolaşım ve Bağışıklık Sistemi', 'Solunum Sistemi', 'Boşaltım Sistemi', 'Üriner Sistem', 'Komünite ve Popülasyon Ekolojisi', 'Genden Proteine', 'Canlılarda Enerji Dönüşümleri', 'Bitki Biyolojisi', 'Canlılar ve Çevre'] }
};

// Node.js'in anlayacağı şekilde dışa aktarma
module.exports = { subjects };